// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonWebApi_Auth0.Models;

namespace PokemonWebApi_Auth0.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20211108154406_PostgresMigration")]
    partial class PostgresMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AbilityPokedex", b =>
                {
                    b.Property<int>("AblilitesId")
                        .HasColumnType("integer");

                    b.Property<int>("PokedexesId")
                        .HasColumnType("integer");

                    b.HasKey("AblilitesId", "PokedexesId");

                    b.HasIndex("PokedexesId");

                    b.ToTable("AbilityPokedex");
                });

            modelBuilder.Entity("PokedexType", b =>
                {
                    b.Property<int>("PokedexesId")
                        .HasColumnType("integer");

                    b.Property<int>("TypesId")
                        .HasColumnType("integer");

                    b.HasKey("PokedexesId", "TypesId");

                    b.HasIndex("TypesId");

                    b.ToTable("PokedexType");
                });

            modelBuilder.Entity("PokemonWebApi_Auth0.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokemonWebApi_Auth0.Models.Pokedex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<int>("Evolves_from")
                        .HasColumnType("integer");

                    b.Property<int>("Evolves_to")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Image_link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pokedexes");
                });

            modelBuilder.Entity("PokemonWebApi_Auth0.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("AbilityPokedex", b =>
                {
                    b.HasOne("PokemonWebApi_Auth0.Models.Ability", null)
                        .WithMany()
                        .HasForeignKey("AblilitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonWebApi_Auth0.Models.Pokedex", null)
                        .WithMany()
                        .HasForeignKey("PokedexesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokedexType", b =>
                {
                    b.HasOne("PokemonWebApi_Auth0.Models.Pokedex", null)
                        .WithMany()
                        .HasForeignKey("PokedexesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonWebApi_Auth0.Models.Type", null)
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
